version: '1.4'
services:
  application_gortrans:
    build:
      dockerfile: Dockerfile
    depends_on:
      database_mariadb:
        condition: service_healthy
    networks:
      - backend
    ports:
      - '8082:8082'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  database_mariadb:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: testpass
    networks:
      - backend
    volumes:
      - ./src/main/resources/sql/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysql --user=root --password=testpass -e 'show databases'" ]
      start_period: 10s
      interval: 3s
      timeout: 3s
      retries: 3
networks:
  backend:
    driver: bridge