USE DEP_1;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_2;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_3;
CREATE INDEX idx_lesson_date  ON lesson (DATE);
USE DEP_4;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_5;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_6;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_7;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_8;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_9;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_10;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_11;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_12;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_13;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_14;
CREATE INDEX idx_lesson_date  ON lesson (date);
USE DEP_15;
CREATE INDEX idx_lesson_date  ON lesson (date);