USE DEP_1;
CREATE INDEX idx_student_name ON student (name);
USE DEP_2;
CREATE INDEX idx_student_name ON student (name);
USE DEP_3;
CREATE INDEX idx_student_name ON student (name);
USE DEP_4;
CREATE INDEX idx_student_name ON student (name);
USE DEP_5;
CREATE INDEX idx_student_name ON student (name);
USE DEP_6;
CREATE INDEX idx_student_name ON student (name);
USE DEP_7;
CREATE INDEX idx_student_name ON student (name);
USE DEP_8;
CREATE INDEX idx_student_name ON student (name);
USE DEP_9;
CREATE INDEX idx_student_name ON student (name);
USE DEP_10;
CREATE INDEX idx_student_name ON student (name);
USE DEP_11;
CREATE INDEX idx_student_name ON student (name);
USE DEP_12;
CREATE INDEX idx_student_name ON student (name);
USE DEP_13;
CREATE INDEX idx_student_name ON student (name);
USE DEP_14;
CREATE INDEX idx_student_name ON student (name);
USE DEP_15;
CREATE INDEX idx_student_name ON student (name);