USE DEP_1;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_2;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_3;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_4;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_5;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_6;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_7;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_8;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_9;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_10;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_11;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_12;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_13;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_14;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;
USE DEP_15;
ALTER TABLE lesson MODIFY isHeld TINYINT(1) NULL;
ALTER TABLE lesson
    ADD status varchar(20) NOT NULL DEFAULT 'PLANNED' ;
UPDATE lesson
SET status = CASE isHeld WHEN TRUE THEN 'HELD' ELSE status  END ;