USE DEP_1;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_2;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_3;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_4;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_5;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_6;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_7;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_8;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_9;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_10;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_11;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_12;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_13;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_14;
DROP INDEX idx_lesson_date ON lesson;
USE DEP_15;
DROP INDEX idx_lesson_date ON lesson;